import { Integration } from './integration-types'

export const integrations: Integration[] = [
  {
    id: 'github',
    name: 'GitHub',
    description: 'Connect your GitHub repositories for code insights and collaboration tracking',
    logo: 'Github',
    status: 'connected',
    lastSync: '2 hours ago',
    statistics: {
      synced: 2547,
      updated: 342,
      errors: 0,
    },
    category: 'development',
    color: 'rgb(79, 84, 92)',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Sync your emails for conversation context and team communication',
    logo: 'Mail',
    status: 'connected',
    lastSync: '30 minutes ago',
    statistics: {
      synced: 5843,
      updated: 124,
      errors: 0,
    },
    category: 'communication',
    color: 'rgb(234, 67, 53)',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Integrate Slack channels for conversation history and team activities',
    logo: 'MessageSquare',
    status: 'connected',
    lastSync: '5 minutes ago',
    statistics: {
      synced: 8932,
      updated: 1203,
      errors: 2,
    },
    category: 'communication',
    color: 'rgb(62, 45, 143)',
  },
  {
    id: 'calendar',
    name: 'Google Calendar',
    description: 'Sync calendar events for scheduling and meeting context',
    logo: 'Calendar',
    status: 'connected',
    lastSync: '15 minutes ago',
    statistics: {
      synced: 342,
      updated: 45,
      errors: 0,
    },
    category: 'productivity',
    color: 'rgb(66, 133, 244)',
  },
  {
    id: 'drive',
    name: 'Google Drive',
    description: 'Connect to Drive for document and file access',
    logo: 'FileText',
    status: 'disconnected',
    statistics: {
      synced: 0,
      updated: 0,
      errors: 0,
    },
    category: 'storage',
    color: 'rgb(52, 168, 83)',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Integrate Notion workspaces for knowledge base synchronization',
    logo: 'Database',
    status: 'pending',
    lastSync: '1 hour ago',
    statistics: {
      synced: 1243,
      updated: 234,
      errors: 3,
    },
    category: 'productivity',
    color: 'rgb(15, 15, 15)',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Connect Discord servers for community and team interaction tracking',
    logo: 'Zap',
    status: 'disconnected',
    statistics: {
      synced: 0,
      updated: 0,
      errors: 0,
    },
    category: 'communication',
    color: 'rgb(88, 101, 242)',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Integrate Linear for issue tracking and project management',
    logo: 'CheckSquare',
    status: 'error',
    lastSync: '1 day ago',
    statistics: {
      synced: 456,
      updated: 0,
      errors: 12,
    },
    category: 'productivity',
    color: 'rgb(95, 95, 95)',
  },
]
